name: seu_projeto
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  moor_flutter: ^4.0.0
  moor: ^4.0.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
